version: '3'
services:
  nginx:
    #build: ./nginx
    image: lyx554073858/lnmp:v2-nginx1.14.2-alpine
    depends_on:
      - php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
    networks:
      - frontend
    restart: always
    container_name: nginx

  php:
    #build: ./php
    image: lyx554073858/lnmp:v2-php7.2-fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/www:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - frontend
      - backend  
    restart: always
    container_name: php

  mysql:
    #build: ./mysql
    image: lyx554073858/lnmp:v2-mysql5.7.24
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    #build: ./redis
    image: lyx554073858/lnmp:v2-redis4.0.11-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.log:/usr/local/redis/redis.log
    networks:
      - backend
    restart: always
    container_name: redis

networks:
  frontend:
  backend:
    
